name: Add to project

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/Kilexmommm/projects/9
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
